### ISSUE TITLE
Running apollo under Windows results in weird USB "permission denied" errors

### ISSUE THREAD

**Issue by supersat** [greatscottgadgets/luna#142]
I suspect somewhere a handle to the apollo USB device isn't being released, and libusb is returning "permission denied" when a second handle attempts to be obtained.

I believe the first time it tries to acquire this handle is when it queries the apollo for the board version. Manually specifying LUNA_PLATFORM=luna.gateware.platform.luna_r0_4:LUNAPlatformRev0D4 bypasses this check and the gateware uploads successfully.

**Comment by supersat** [comment]
This should be fixed after merging https://github.com/greatscottgadgets/apollo/pull/6 and #144

**Comment by martinling** [comment]
This is all working now.
