### ISSUE TITLE
implement target speed detection

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/luna#148]
We have the ability to capture USB packets for analysis at High-Speed or Full-Speed, but we require the user to specify the speed when initiating capture. We want the speed to be detected automatically and to allow capture to be launched with speed unspecified.

**Comment by martinling** [comment]
The analyzer gateware has moved to the Cynthion repository; this issue is now tracked at https://github.com/greatscottgadgets/cynthion/issues/53.
