### ISSUE TITLE
Low Speed USB capture

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/luna#150]
Implement capture of Low Speed USB for analysis

**Comment by martinling** [comment]
Low speed capture seems to be working correctly for me, following the setup and capture procedure I described on #164 with `setup-analyzer.py` changed to `build_and_configure(USB_SPEED_LOW)`.

Was there something specific known to be wrong with this?

**Comment by martinling** [comment]
Closing this since the analyzer gateware has moved to Cynthion and low speed capture works fine.
