### ISSUE TITLE
nmigen project name changed to amaranth.

### ISSUE THREAD

**Issue by lethalbit** [greatscottgadgets/luna#153]
This is more of a heads up than an issue, but the [nMigen project has officially been rebranded amaranth-lang](https://twitter.com/whitequark/status/1469267241355124737) (new home is [at amaranth-lang](https://github.com/amaranth-lang)), and as such that would need to be updated here.

The core amaranth package and the -boards package have a thin compat layer but the -soc and -stdio packages do not.

Also there are some things which the Luna gateware uses that are not included in the compat layer, such as the `nmigen._unused` module so that import breaks.

All things considered it should be a fairly simple forward port, so this is just a heads-up to the change

**Comment by straithe** [comment]
Thank you for thus update! We appreciate the heads up.
