### ISSUE TITLE
possability of adding Discussions

### ISSUE THREAD

**Issue by bm16ton** [greatscottgadgets/luna#173]
It would be great if you added a Discussions. A while back i looked if any new resources had comeout about sniffing usb etc and sad to see by and large it was same resources from 10years prior, except most of the software mentioned was outdated or no longer existed. A place to share info might be the shot in the arm the subject desperatly needs. I did google to see if you guys had a forum but if you do it didnt come up. Love you guys, love your work (especially the wiggler) thank you for what you do!

**Comment by straithe** [comment]
Thank you for reaching out! You are welcome to join our Discord (https://discord.gg/rsfMw3rsU8) to hang out with us and friends of GSG or you may follow any of our social media accounts listed on greatscottgadgets.com to get updates on what we are doing. We will not be adding discussions.
