### ISSUE TITLE
design an r0.3

### ISSUE THREAD

**Issue by ktemkin** [greatscottgadgets/luna#18]
Some potential changes for r0.3:

- [x] Re-spec 3V3 regulator to reduce ripple; or at the least, remove its bypass capacitor.
- [x] Improve grounding / thermal connections for the USB PHYs.
- [x] Potentially switch between the active-high and active-low versions of our load switches / switch the load configuration to reduce leakage.
- [x] Replace the USB PHY pull-up resistors with pull-down ones.
- [x] Replace the 60MHz oscillator with the cheaper / lower-jitter `SIT1602BC-73-33E-60.000000E`.
- [x] Re-evaluate availability and see if switching the 1V1 regulator to its larger package (`EF` vs `EE`) makes sense.
- [x] Clean up redundant input caps (C6, C40, C47) on 3V3 regulator (U3).
- [x] Remove redundant C45.
- [x] Change R17, R19, R21 to 5%.
- [x] Add TC2030-NL footprint for SWD.
- [x] Improve pin 1 marking of oscillator Y1 footprint.
- [x] Add "Substitution" BOM field ("any equivalent" for most passives).
- [x] Select LED components and matching series resistors.
- [x] Move LED silkscreen labels closer to LEDs.
- [x] Connect `PROGRAM_N` to a nearby 3V3 FPGA I/O to allow for easier Debug Controller-less operation.
- [x] Potentially swap the SAMD21 with a SAMD11, for cost reduction.
- [x] Potentially move to USB-C connectors, instead of microUSB.

**Comment by ktemkin** [comment]
@mossmann assigning you `r0.3`-related tasks, for now. Feel free to re-assign. :)

**Comment by mossmann** [comment]
Work in progress is in this branch: https://github.com/mossmann/luna/tree/r0.3

**Comment by mossmann** [comment]
I've removed bypass capacitor C52 from the +3V3 regulator at least as a temporary measure. I will likely replace the regulator entirely after some testing.

**Comment by ktemkin** [comment]
Added one more bullet:

- Connect PROGRAM_N to a nearby 3V3 FPGA I/O to allow for easier Debug Controller-less operation.

This will allow the FPGA to trigger its own reconfiguration.

**Comment by mossmann** [comment]
I resolved the load switch issue primarily by reducing the resistance of the pull-up and pull-down resistors on the load switch enable pins.
