### ISSUE TITLE
Failed to run command poetry install

### ISSUE THREAD

**Issue by bigniudiy** [greatscottgadgets/luna#181]
I followed the documentation and installed the dependencies, but an error was reported when I ran the command poetry install. It seems that the version of lambdasoc cannot match. What should I do?

> kevin@kevin-virtual-machine:~/workspace/luna$ poetry install
Installing dependencies from lock file

> Because lambdasoc (0.1.dev27+gefd5442) @ git+https://github.com/ktemkin/lambdasoc.git@HEAD depends on nmigen (*) which doesn't match any versions, lambdasoc is forbidden.
So, because luna depends on lambdasoc (0.1.dev27+gefd5442) @ git+https://github.com/ktemkin/lambdasoc.git, version solving failed.

**Comment by martinling** [comment]
You can also install the package with `pip install .`

We may well replace the use of Poetry. There have been quite a few difficulties with it, and it's not as necessary now that more of the dependencies have stable releases. But there isn't a firm decision as yet.
