### ISSUE TITLE
applets/interactive-test.py needs prompt_toolkit package

### ISSUE THREAD

**Issue by jeremyherbert** [greatscottgadgets/luna#195]
Hi,

In the docs it says to run `applets/interactive-test.py` to test LUNA, but this file relies on the `prompt_toolkit` package which is not listed in the `pyproject.toml` in the normal dependencies section. `pip install prompt_toolkit` fixes the issue.

Feel free to close this as wont-fix if you understandably don't want to add the extra dependency, but it might be good to add to the docs that you need to install the package anyway.

**Comment by martinling** [comment]
This is actually an Apollo bug, and I've opened https://github.com/greatscottgadgets/apollo/issues/35 to track it.

Closing it here on the LUNA side.
