### ISSUE TITLE
is USB3 SuperSpeed supported by Cynthion?

### ISSUE THREAD

**Issue by MaorRakach** [greatscottgadgets/luna#274]
When I try to run examples/usb/superspeed/simple_device.py I get this error:
`
    raise ValueError(f"Platform {self.name} has no default USB3 PHY; cannot create one automatically.")
ValueError: Platform Cynthion r1.4 has no default USB3 PHY; cannot create one automatically.
`

If want to work with USB3 & Cynthion, where should I start

**Comment by mossmann** [comment]
Superspeed is not supported on Cynthion. Cynthion is a USB 2.0 platform: https://greatscottgadgets.com/cynthion/

SuperSpeed has been known to work on some platforms listed here: https://luna.readthedocs.io/en/latest/features.html#reference-boards
