### ISSUE TITLE
Minor formatting issue in bringup guide

### ISSUE THREAD

**Issue by mithro** [greatscottgadgets/luna#28]
Usage of Markdown in rst file not going to work :-) -- https://luna.readthedocs.io/en/latest/hardware/bringup_guide.html

![Screenshot from 2020-07-06 12-26-00](https://user-images.githubusercontent.com/21212/86632228-f6c5ca80-bf83-11ea-950e-5585a0983c95.png)

**Comment by ktemkin** [comment]
Oops! That originally was from the Wiki -- I used `pandoc` to convert it into rst; dunno what happened there. :)

Will fix; thanks.
