### ISSUE TITLE
SyncSerialILA domain selection doesn't work

### ISSUE THREAD

**Issue by miek** [greatscottgadgets/luna#34]
`SyncSerialILA.__init__` extracts the `domain` argument and then resets it to `sync` before instantiating an `IntegratedLogicAnalyzer` (with the intention of wrapping it in `DomainRenamer`?), but the `DomainRenamer` is in `IntegratedLogicAnalyzer` itself so it never ends up in the correct domain.

For now I've deleted line 315 (that was resetting the domain arg to `sync`) and that seems to work well, but I wasn't sure whether that was the right fix. https://github.com/greatscottgadgets/luna/blob/d9c0a41996614dd8698341b46bd1df6482f27f5c/luna/gateware/debug/ila.py#L311-L315

**Comment by ktemkin** [comment]
Should be fixed (added the intended `DomainRenamer`).
