### ISSUE TITLE
ILA output incorrect if bits_per_word is not a power of 2

### ISSUE THREAD

**Issue by miek** [greatscottgadgets/luna#35]
If I setup a SyncSerialILA with signals such that `bits_per_word` is calculated to be something that isn't a power of 2 (eg: 96, 160, 192, etc.), then the output VCD ends up all wrong. I haven't been able to spot a pattern in what's going wrong yet, or narrow it down in the code.

To reproduce, edit `examples/debugging/basic_ila.py` to set the counter size to 65 and observe that the VCD is odd:
![ila-65bits_000](https://user-images.githubusercontent.com/578095/88467013-497f0c00-ceca-11ea-8cbd-6a01357bd8ed.png)

set the counter size to 64 and all is good:
![ila-64bits](https://user-images.githubusercontent.com/578095/88467018-6287bd00-ceca-11ea-8a09-024ca2773d4b.png)

**Comment by ktemkin** [comment]
Should be fixed -- let me know if you still have issues. :)
