### ISSUE TITLE
FaceDancer: Implement Initial Design Specification / RFP

### ISSUE THREAD

**Issue by ktemkin** [greatscottgadgets/luna#68]
Create an initial design document describing a FaceDancer backend for LUNA.

This should:

- [x] Include plans for the core backend.
- [ ] Accommodate future FPGA acceleration, where possible. 
- [ ] Accommodate fancy USBProxy enhancements.

**Comment by antoinevg** [comment]
Latest version can be found in:

https://github.com/antoinevg/GSG/blob/main/luna/design/rfp.md
