### ISSUE TITLE
usb3343 pin matching

### ISSUE THREAD

**Issue by dzyko** [greatscottgadgets/luna#7]
![usb3343](https://user-images.githubusercontent.com/26501765/77093875-b36b3e80-6a1c-11ea-8106-5f8b02b51848.png)

Please check pin for USB D+ and D-
Does it work?

**Comment by ktemkin** [comment]
Hi, @dzyko:

The locations of D+ and D- are configurable -- you can swap them by writing to a PHY register. These locations do indeed work. :)

**Comment by ktemkin** [comment]
A little bit of further elaboration: swapping the pins this way is intended to keep the D+ and D- traces from crossing over; allowing us to maintain their mutual impedance and length matching as much as we can. :)
